# Generated by Django 3.0.2 on 2020-01-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='Data di creazione'),
        ),
    ]
