# Generated by Django 3.0.2 on 2020-01-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0002_component_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='input_ports',
            field=models.TextField(blank=True, null=True, verbose_name='Porte di input'),
        ),
        migrations.AddField(
            model_name='component',
            name='output_ports',
            field=models.TextField(blank=True, null=True, verbose_name='Porte di output'),
        ),
        migrations.AlterField(
            model_name='component',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Data di creazione'),
        ),
    ]
