# Generated by Django 3.0.2 on 2020-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0003_auto_20200112_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='architecture_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Architettura'),
        ),
        migrations.AddField(
            model_name='component',
            name='entity_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome entità'),
        ),
    ]
