# Generated by Django 3.0.2 on 2020-01-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0004_auto_20200112_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structural',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('component_list', models.TextField(verbose_name='Componenti')),
            ],
        ),
    ]
