# Generated by Django 3.0.2 on 2020-01-13 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0005_structural'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data di creazione'),
            preserve_default=False,
        ),
    ]
