# Generated by Django 3.0.2 on 2020-01-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0006_structural_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural',
            name='mappings',
            field=models.TextField(blank=True, null=True, verbose_name='Mappature'),
        ),
    ]
