# Generated by Django 3.0.2 on 2020-01-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vhdl', '0007_structural_mappings'),
    ]

    operations = [
        migrations.AddField(
            model_name='structural',
            name='architecture_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome architettura'),
        ),
        migrations.AddField(
            model_name='structural',
            name='entity_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome entità'),
        ),
    ]
